# Generated by Django 4.2.4 on 2023-08-28 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="user_name",
            field=models.CharField(default="default-user", max_length=50, unique=True),
        ),
    ]
