# Generated by Django 4.2.4 on 2023-08-28 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_customuser_user_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="user_name",
            new_name="username",
        ),
    ]
